const searchList = [
  {
    'bookname':"全球十大教父",
    'image':'https://bkimg.cdn.bcebos.com/pic/8718367adab44aed95fdcd3dbd1c8701a08bfbbc?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'讲述了以维托·唐·柯里昂为首的黑帮家族的发展过程以及柯里昂的小儿子迈克如何接任父亲成为黑帮首领的故事。'
  },
  {
    'bookname':"陈秉德写意山水",
    'image':'http://img3.imgtn.bdimg.com/it/u=3112442899,144896696&fm=26&gp=0.jpg',
    'descrip':'写了一些意思，画了一些山水'
  },
    {
    'bookname':"冀有泉水墨胡杨",
    'image':'https://bkimg.cdn.bcebos.com/pic/8718367adab44aed95fdcd3dbd1c8701a08bfbbc?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'讲述了以维托·唐·柯里昂为首的黑帮家族的发展过程以及柯里昂的小儿子迈克如何接任父亲成为黑帮首领的故事。'
  },
    {
    'bookname':"缤纷的水世界",
    'image':'https://bkimg.cdn.bcebos.com/pic/8718367adab44aed95fdcd3dbd1c8701a08bfbbc?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'讲述了以维托·唐·柯里昂为首的黑帮家族的发展过程以及柯里昂的小儿子迈克如何接任父亲成为黑帮首领的故事。'
  },
    {
    'bookname':"八十天环游地球",
    'image':'https://bkimg.cdn.bcebos.com/pic/8718367adab44aed95fdcd3dbd1c8701a08bfbbc?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'讲述了以维托·唐·柯里昂为首的黑帮家族的发展过程以及柯里昂的小儿子迈克如何接任父亲成为黑帮首领的故事。'
  },
  {
    'bookname':"十二五”国家级专项规划汇编",
    'image':'https://bkimg.cdn.bcebos.com/pic/8718367adab44aed95fdcd3dbd1c8701a08bfbbc?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'讲述了以维托·唐·柯里昂为首的黑帮家族的发展过程以及柯里昂的小儿子迈克如何接任父亲成为黑帮首领的故事。'
  },
    {
    'bookname':"交响乐欣赏十八讲",
    'image':'https://bkimg.cdn.bcebos.com/pic/8718367adab44aed95fdcd3dbd1c8701a08bfbbc?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'讲述了以维托·唐·柯里昂为首的黑帮家族的发展过程以及柯里昂的小儿子迈克如何接任父亲成为黑帮首领的故事。'
  },
    {
    'bookname':"巴斯克维尔的猎犬（侦探小说）",
    'image':'https://bkimg.cdn.bcebos.com/pic/8718367adab44aed95fdcd3dbd1c8701a08bfbbc?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'讲述了以维托·唐·柯里昂为首的黑帮家族的发展过程以及柯里昂的小儿子迈克如何接任父亲成为黑帮首领的故事。'
  },
    {
    'bookname':"繁星春水",
    'image':'https://bkimg.cdn.bcebos.com/pic/8718367adab44aed95fdcd3dbd1c8701a08bfbbc?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'讲述了以维托·唐·柯里昂为首的黑帮家族的发展过程以及柯里昂的小儿子迈克如何接任父亲成为黑帮首领的故事。'
  },
    {
    'bookname':"孝经.二十四孝.弟子规",
    'image':'https://bkimg.cdn.bcebos.com/pic/8718367adab44aed95fdcd3dbd1c8701a08bfbbc?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'讲述了以维托·唐·柯里昂为首的黑帮家族的发展过程以及柯里昂的小儿子迈克如何接任父亲成为黑帮首领的故事。'
  },
    {
    'bookname':"山歌如水张鸿全.诗集",
    'image':'https://bkimg.cdn.bcebos.com/pic/8718367adab44aed95fdcd3dbd1c8701a08bfbbc?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'讲述了以维托·唐·柯里昂为首的黑帮家族的发展过程以及柯里昂的小儿子迈克如何接任父亲成为黑帮首领的故事。'
  },
  {
    'bookname':"水浒传",
    'image':'https://bkimg.cdn.bcebos.com/pic/241f95cad1c8a786e78cf62f6409c93d70cf5068?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'讲述的是宋朝宋徽宗时期皇帝昏庸、奸臣当道、官府腐败、贪官污吏陷害忠良，弄得民不聊生，许多正直善良的人被官府逼得无路可走，被迫奋起反抗，最终108条好汉聚义梁山泊，但随后宋江对朝廷的投降使得一场轰轰烈烈的农民起义最后走向失败的故事。'
  },
    {
    'bookname':"西游记",
    'image':'https://bkimg.cdn.bcebos.com/pic/960a304e251f95ca5de2baafc6177f3e67095297?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'讲述的是孙悟空、猪八戒、沙僧辅保大唐高僧玄奘去西天取经，师徒四人一路抢滩涉险，降妖伏怪，历经八十一难，取回真经，终修正果的故事'
  },
    {
    'bookname':"红楼梦",
    'image':'https://bkimg.cdn.bcebos.com/pic/d01373f082025aaff3cec4b8f1edab64024f1ac0?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'以贾、史、王、薛四大家族的兴衰为背景，以富贵公子贾宝玉为视角，以贾宝玉与林黛玉、薛宝钗的爱情婚姻悲剧为主线，描绘了一批举止见识出于须眉之上的闺阁佳人的人生百态，展现了真正的人性美和悲剧美，可以说是一部从各个角度展现女性美以及中国古代社会世态百相的史诗性著作。'
  },
    {
    'bookname':"三国演义",
    'image':'https://bkimg.cdn.bcebos.com/pic/622762d0f703918f79cb435b5b3d269759eec40d?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'描写了从东汉末年到西晋初年之间近百年的历史风云，以描写战争为主，诉说了东汉末年的群雄割据混战和魏、蜀、吴三国之间的政治和军事斗争，最终司马炎一统三国，建立晋朝的故事。反映了三国时代各类社会斗争与矛盾的转化，并概括了这一时代的历史巨变，塑造了一群叱咤风云的三国英雄人物。'
  },
];

const recentSuggest = [
  {
    'bookname':"西游记",
    'image':'https://bkimg.cdn.bcebos.com/pic/960a304e251f95ca5de2baafc6177f3e67095297?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'讲述的是孙悟空、猪八戒、沙僧辅保大唐高僧玄奘去西天取经，师徒四人一路抢滩涉险，降妖伏怪，历经八十一难，取回真经，终修正果的故事'
  },
    {
    'bookname':"红楼梦",
    'image':'https://bkimg.cdn.bcebos.com/pic/d01373f082025aaff3cec4b8f1edab64024f1ac0?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'以贾、史、王、薛四大家族的兴衰为背景，以富贵公子贾宝玉为视角，以贾宝玉与林黛玉、薛宝钗的爱情婚姻悲剧为主线，描绘了一批举止见识出于须眉之上的闺阁佳人的人生百态，展现了真正的人性美和悲剧美，可以说是一部从各个角度展现女性美以及中国古代社会世态百相的史诗性著作。'
  },
  {
    'bookname':"三国演义",
    'image':'https://bkimg.cdn.bcebos.com/pic/622762d0f703918f79cb435b5b3d269759eec40d?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg',
    'descrip':'描写了从东汉末年到西晋初年之间近百年的历史风云，以描写战争为主，诉说了东汉末年的群雄割据混战和魏、蜀、吴三国之间的政治和军事斗争，最终司马炎一统三国，建立晋朝的故事。反映了三国时代各类社会斗争与矛盾的转化，并概括了这一时代的历史巨变，塑造了一群叱咤风云的三国英雄人物。'
  },
];

